City-of-Helsinki/youth-membership-ui

.gitlab-ci.yml
Api-tokens query was failing in test env because of missing slashes at the end of the configured URLs. I added the slashes.
=> OM-236 | Add slashes to test env urls

.env, README.md
The API was previously called "profiles". Changed the configuration files to
reflect the current name "helsinkiprofile".
=> OM-255 | Change the backend API name

src/pages/membership/components/approveYouthProfile/ApproveYouthProfile.tsx, src/pages/membership/components/approveYouthProfileForm/ApproveYouthProfileForm.tsx
Because `birthDate` field was converted to locale format (dd.mm.yyyy) in `ApproveYouthProfile` component, it was in wrong format for `differenceInYears` method which would result it returning `NaN`. BirthDate is now passed down in right format (yyyy-mm-dd) to `ApproveYouthProfileForm`.
This component among many others would benefit from unit testing.
=> OM - 402| Photo permission display

src/pages/membership/components/membershipInformation/MembershipInformation.tsx
After creating new mutation for fetching data in MembershipInformation component, I forgot to change query that is re-fetched if mutation is successful.
=> Changed query that is re-fetched on renew.

.env.development, .env.test, .gitlab-ci.yml, package.json, src/pages/membership/components/membershipInformation/MembershipInformation.tsx
The URL for the profile backend was changed recently to profiili-api.* so I
changed it to the appropriate places in the UI's configuration. I also
changed the production config, since that was anyway pointing to the test
environment which is wrong.
=> OM-620 | Fix backend URL

src/pages/membership/components/youthProfileForm/YouthProfileForm.tsx, src/pages/membership/components/youthProfileForm/__tests__/YouthProfileForm.test.tsx
Fixed issue where under 18 years old could change / remove approver information while editing profile. Now that age is determined by value coming from props, I added few tests based on user's age.
=> OM 745 | Youth can remove approver information

README.md, package.json, yarn.lock
Adds `yarn update-translations` script from [helsinki-utils-js](https://github.com/City-of-Helsinki/helsinki-utils-js). It creates new translation message files based on the current version of translation source and overwrites existing files with them.
I haven't fetched the latest translations in this PR--should I?
=> OM-542 | Add update-translations script

src/pages/membership/components/editYouthProfile/EditYouthProfile.tsx, src/pages/membership/helpers/__tests__/updateProfileMutationVariables.test.ts, src/pages/membership/helpers/updateProfileMutationVariables.ts
- When editing profile, `photoUsageApproved` field is sent to backend.
- When adding missing field I noticed update mutation was missing Sentry capturing so I added that as well.
=> YM-227 | PhotoUsageApproved is now passed to backend.

src/pages/membership/components/confirmApprovingYouthProfile/__tests__/ConfirmApprovingYouthProfile.test.tsx, src/pages/membership/components/confirmApprovingYouthProfile/__tests__/__snapshots__/ConfirmApprovingYouthProfile.test.tsx.snap
Added test for `ConfirmApprovingYouthProfile` component. The component is really simple so simple snapshot test should be enough.
=> YM-228 | Tests for ConfirmApprovingYouthProfile

package.json, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/membership/components/youthProfileForm/YouthProfileForm.tsx, src/pages/membership/components/youthProfileForm/__tests__/YouthProfileForm.test.tsx, yarn.lock
- Added `postcode-validator` for validation
- Moved country selection box to be before other address information.
- PostalCode inputMode changes based on current languageCode 
- Added tests for checking inputMode changes
- Because implementing tests with formik currently results to pile of errors, I will add tests testing validation later.
=> OM-849 | Improve postalCode validation

src/App.tsx, src/auth/constants/authConstants.ts, src/auth/logout.ts, src/pages/membership/helpers/getCookie.ts
- If multiple tabs are open, user actions (login / logout) will affect all tabs.
- While doing this I ran into bug, where `birthDate` cookie would have false value e.g `;  _randomValue`. Removing `.` from regex improved matching and fixed the issue. It's really small fix so I though I would apply it here.
=> YM-222 | User session

src/pages/membership/components/createYouthProfile/__tests__/CreateYouthProfile.test.tsx
Wrapper language changes inside `act`.
After these changes errors show [here](https://travis-ci.com/github/City-of-Helsinki/youth-membership-ui/builds/169548591) should be fixed.
=> FIX | Component update not wrapper in act

src/pages/membership/components/membershipDetails/__tests__/MembershipDetails.test.tsx
Tests for `MembershipDetails` component. This component is used to just display user information. I would have liked to make snapshot test, but Apollo's `MockedProvider` randomly adds or removes `SubscriptionObserver` from snapshot, causing snapshot to change on every update. Instead I wrote a simple tests that checks all that all possible fields are present.
=> YM-242 | Test for MembershipDetails

src/pages/membership/components/youthProfileForm/YouthProfileForm.tsx
The phone number and all the approver fields were not validated on
blur, because they had not been transitioned to use FormikTextInput.
Same PR as this one https://github.com/City-of-Helsinki/youth-membership-ui/pull/119 but with a different branch name so that Travis will run all checks.
=> YM-243 | Fix fields not being validated on blur

public/robots.txt
Removed `Disallow` parameter from `robot.txt` file.
=> YM-293 | Remove robot.txt disallow parameter

src/domain/youthProfile/form/YouthProfileForm.tsx, src/domain/youthProfile/form/youthProfileForm.module.css
This also fixes YM-263, as now both terms boxes will be toggled by clicking on the label.
=> YM-263 | Use same terms component for both forms

CHANGELOG.md, src/common/components/dateInput/DateInput.tsx, src/common/components/dateInput/InputWithoutSpinners.tsx, src/common/components/dateInput/inputWithoutSpinners.module.css
After this change the birthday input should no longer show spinners on Firefox.
=> YM-302 | Hide number input spinners

src/common/components/arrayFieldTemplate/ArrayFieldTemplate.tsx, src/common/components/arrayFieldTemplate/arrayFieldTemplate.module.css, src/common/components/stack/Stack.tsx, src/domain/youthProfile/form/YouthProfileAddressTemplate.tsx, src/domain/youthProfile/form/YouthProfileApproverFields.tsx, src/domain/youthProfile/form/YouthProfileBasicInformationFields.tsx, src/domain/youthProfile/form/YouthProfileForm.tsx, src/domain/youthProfile/form/YouthProfileFormGrid.tsx, src/domain/youthProfile/form/youthProfileAddressTemplate.module.css, src/domain/youthProfile/form/youthProfileForm.module.css, src/domain/youthProfile/form/youthProfileFormGrid.module.css
In this PR I add a common component for array fields. When we have a single field, we can ensure that the array fields behave and look roughly the same.
I also refactored the styles to make use of grids. That way we have less markup and less complex markup. These changes also made it easier to make the array fields consistent with the other fields. Further tweaks to the spacing should now be easier to do.
=> Use same presentation logic for array fields

CONTRIBUTING.md
Updated the contribution guidelines so that it contains our developer email group.
=> YM-309 | Add youth membership email group to contributing.md

CHANGELOG.md, src/domain/youthProfile/approve/ApproveYouthProfilePage.tsx, src/domain/youthProfile/approve/confirmApprovingYouthProfile.module.css
Previously the photo usage approval field was not sent when a profile
was accepted. This commit adds it to the request we make to GraphQL.
I also removed the big margin the acceptance approval view had which Anniina mentioned earlier.
=> YM-318 | Fix photo usage control in approval view

src/common/components/termsField/TermsField.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Updated the latest translations from the Excel which now contained the link
to Helsinki profile privacy policy + updated texts for terms approval.
Changed the terms approval so that it now adds a link which points to the
Helsinki profile privacy policy so that the user is at least minimally
notified of that registry.
=> YM-320 | Add link to Helsinki profile privacy policy

CHANGELOG.md, package.json, src/common/test/membershipDetailsData.ts, src/domain/membership/graphql/MembershipDetailsFragment.graphql, src/graphql/generatedTypes.ts
Because `MembershipDetailsFragment` was missing profile ID, it caused Apollo cache to crash when fetching new information.
=> YM-322 | Fix profile information page crash

CHANGELOG.md, src/domain/youthProfile/approve/ApproveYouthProfile.tsx, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/ApproveYouthProfilePage.tsx, src/domain/youthProfile/approve/__test__/ApproveYouthProfileForm.test.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/form/YouthProfileApproverFields.tsx, src/domain/youthProfile/form/YouthProfileForm.tsx, src/domain/youthProfile/youthProfileSchemas.ts
These changes add additional contact persons into the approval form. The approver is now able to add, remove or edit additional contact persons.
I refactored the code to be able to use the same field definitions as in `youthProfile/form/YouthProfileApproverFields.tsx`.
I also moved the schemas from `youthProfile/form/youthProfileFormSchemas.ts` into `youthProfile/youthProfileSchemas.ts` and used those definitions in the approve form.
=> YM-180 | Allow approver to edit additional contact persons

CHANGELOG.md, src/common/components/layout/PageLayout.tsx, src/common/components/layout/header/Header.tsx, src/domain/app/AppRoutes.tsx
After this change the header in the approval view should no longer have a user menu and the logo nor the name of the service should link the user to the home page.
I ended up adopting the following pattern
```jsx
<Switch>
<Route path={['/approve/:token']}>
<PageLayout variant="approver">
<Switch>
{/* Routes... */}
</Switch>
</PageLayout>
</Route>
<Route>
<PageLayout>
<Switch>
{/* Routes... */}
</Switch>
</PageLayout>
</Route>
</Switch>
```
In my opinion this is a bit ugly. I'm trying to do two things at the same time which it appears are not that easy to do at the same time: (a) have composable layouts that (b) can be shared between routes.
Why? I want _a_ because without it the architecture is forced to adopt an "extend" approach where logic is added to existing components. Those kind of …
=> YM-332 | Hide user menu and disable links in approval view

src/common/components/layout/InfoPageLayout.tsx, src/common/components/layout/PageContent.tsx, src/common/components/layout/PageSection.tsx, src/common/components/layout/infoPageLayout.module.css, src/domain/auth/components/oidcCallback/OidcCallback.tsx, src/domain/youthProfile/approve/__test__/ApproveYouthProfilePage.test.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Previously the error handling in the authentication callback didn't handle some known problem cases
* Device time off by more than 5min
* User declines permission
I just copied the logic over from Kukkuu.
The real issue was that the callback used `history.push` when it redirected the user into another view. This left the `/ callback` page into the browser history. We suspect that users sometimes accidentally access this page again when they use the browser's back button to navigate.
I also noticed that we were not using `main` at all, so I added it into the `<PageContent>` component.
=> YM-352 | Improve authentication callback error handling

src/i18n/sv.json
Swedish translation for `addGuardianText` had invalid word.
=> YM-349 | Fix translations

src/domain/youthProfile/form/FormikFocusError.tsx
Scroll to first error was broken. When getting error keys, the order would be pretty much random. I added logic that sorts keys to match the order in which the fields occur in our form. 
Also added scroll handling to `additionalContactPersons`. After #160 is merged, I'll try to write e2e test so the functionality won't break again.
=> YM-362 | Fix scroll to first error

CHANGELOG.md, browser-tests/registrationView.ts
Added `2e2` test for testing "scroll to first error element" functionality. It's added to both "check errors" tests, it will take extra second to execute so I think it should be fine.
I just realised that I haven't remembered to update `CHANGELOG.md`. I included those to this PR as well.
=> YM-362 | Add e2e test for scrolling to first error

src/domain/youthProfile/create/CreateYouthProfile.tsx, src/domain/youthProfile/form/YouthProfileForm.tsx
After this change, even if user spams "Register" button, `createProfile` - mutation is only executed once. `loading` wasn't enough alone, so I added a state that is changed after profile is created.
=> YM-354 | Prevent double submitting form

src/domain/app/AppYouthProfileRoute.tsx, src/domain/youthProfile/create/CreateYouthProfile.tsx, src/domain/youthProfile/create/__tests__/CreateYouthProfilePage.test.tsx
The random `RangeError` was indeed related to invalid date. I added validation, provided by `date-fns`, for all birthDate values. I also tossed extra redirect inside `CreateYouthProfile` component. It seems that logic validating birth date value inside `AppYouthProfileRoute` is only ran when user goes from /login -> (authentication) -> /create. If user refreshes page while /create route is active, it hits the route specified in `AppRoutes` and skips everything else.  
I guess the other solution would be to enforce this more strictly on router level: Move `HasYouthProfile` query to `AppRoutes` and make birth date check there. 
**Testing**
- Input birth date as always.
- Login and be redirected to registration form
- Change `birthDate` cookie value to something that doesn't exists or just …
=> YM-354 | Fix range error

src/domain/app/AppYouthProfileRoute.tsx
Changed `HasYouthProfile` query to use lazy query instead. Query is executed after we make sure user is authenticated.
When user entered website, it would immediately trigger `HasYouthProfile` query and cause `[GraphQL error]`. Now that query is only executed after user is authenticated, error shouldn't exist anymore.
[YM-376](https://helsinkisolutionoffice.atlassian.net/browse/YM-376)
Changes has only tested manually by me.
1) With `development` branch, start local environment with `yarn start`.
2) When process is running, enter the site again via address bar. You should see `[GraphQL error]: You don't have permissions` error in the browser console (refreshing won't trigger the error).
3) Change branches and repeat steps 1 & 2. You should not see the previously mentioned error.
=> YM-376 | GraphQL error: You don't have permission

browser-tests/editMembershipInformationView.ts, browser-tests/pages/membershipInformationSelector.ts, src/domain/youthProfile/helpers/youthProfileGetters.ts
Added `e2e` tests for testing profile information edit functionality. While writing these, tests actually pointed that `photoUsagePermission` field changes were not saved even user was at required age. I included that fix to this PR.
More `e2e` tests.
[YM-380](https://helsinkisolutionoffice.atlassian.net/browse/YM-380)
`yarn browser-test` -> all tests pass
1) Add values to `.env` file (if you don't have these you can contact me):
- `REACT_APP_TESTING_USERNAME`
- `REACT_APP_TESTING_PASSWORD`
- `REACT_APP_TESTING_USERNAME_WITH_PROFILE`
2) Login to [profile-admin](https://profiili-api.test.kuva.hel.ninja/admin) and make sure "Uno User" has no profile
3) Start local application `yarn start`
4) Run `yarn browser-test`
5) Delete the created profile to avoid crashing next time tests are run.
=> YM-380 | Modify own information e2e

browser-tests/pages/membershipInformationSelector.ts, browser-tests/pages/registrationFormSelector.ts, browser-tests/registrationView.ts, browser-tests/utils/settings.ts, browser-tests/utils/valueUtils.ts, package.json, yarn.lock
Added `e2e` - tests for testing:
- User under 18 sees "waiting view" after registration
- Approval email is sent
- Re-sending approval email
- Approval view
- User information is shown after profile is approved
More `e2e` - tests.
[YM-410](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
`yarn browser-test` -> all test pass.
1) Add values to `.env` file (if you don't have these you can contact me):
- `REACT_APP_TESTING_USERNAME`
- `REACT_APP_TESTING_PASSWORD`
- `REACT_APP_TESTING_USERNAME_WITH_PROFILE`
- `REACT_APP_MAILOSAUR_API`
- `REACT_APP_MAILOSAUR_SERVER_ID`
2) Login to [profile-admin](https://profiili-api.test.kuva.hel.ninja/admin) and make sure "Uno User" has no profile
3) Start local application `yarn start`
4) Run `yarn browser-test`
5) Delete the created profile …
=> YM-410 | E2e emails and approval

CHANGELOG.md, src/domain/app/AppYouthProfileRoute.tsx, src/domain/membership/information/MembershipInformationPage.tsx, src/domain/membership/useIsMembershipPending.ts, src/domain/youthProfile/approve/ApproveYouthProfilePage.tsx, src/domain/youthProfile/create/CreateYouthProfilePage.tsx, src/domain/youthProfile/sent/SentYouthProfile.tsx, src/graphql/__tests__/handleError.test.ts, src/graphql/client.ts, src/graphql/config.ts, src/graphql/errorCodes.ts, src/graphql/handleError.ts
Previously the Apollo and Sentry integration was done multiple times at
multiple different places in the code. This commit centralizes this
logic by logging errors into Sentry by using the 'onError' field in
Apollo boost's client.
This centralized error handling adds more context to the data we pass
on to Sentry. This makes debugging easier by allowing us to see the
name of the query that caused an error, for instance. This kind of
context couldn't have been added without centralization.
This change also implements a centralized error ignoring mechanism.
We know that we do not want to pass some errors to Sentry, because the
errors we receive are expected. Such error often include for instance
permission related errors. Now such errors can be ignored globally,
making it less likely that we …
=> YM-405 | Centralize Apollo and Sentry integration

.env, .gitignore, .travis.yml, README.md, browser-tests/registrationView.ts, browser-tests/utils/settings.ts, package.json
Adds a new command `browser-test:ci` which runs browser tests in headless mode. Configures this test to be ran in Travis against the cron event.
I also refactored the way in which the application decides between which environment to use. I adopted the pattern that was used in the `admin-ui`, because I assumed that it was never code.
[YM-339](https://helsinkisolutionoffice.atlassian.net/browse/YM-339)
I've tested the `ci` commands locally. However, unfortunately the mailosaurus credentials in the secrets repo have expired an therefore all the test do not pass currently.
Check that browser tests were ran in Travis:
* https://travis-ci.com/github/City-of-Helsinki/youth-membership-ui/jobs/429469738
You can also verify that the failed tests seem to be Mailosaurus related and are not caused by, …
=> YM-339 | Configure browser tests to be ran against cron in Travis

src/common/test/testUtils.tsx, src/domain/membership/details/__tests__/MembershipDetailsPage.test.tsx, src/domain/membership/information/MembershipInformationPage.tsx, src/domain/membership/information/__tests__/MembershipInformationPage.test.tsx, src/domain/youthProfile/create/__tests__/CreateYouthProfilePage.test.tsx, src/domain/youthProfile/edit/EditYouthProfile.tsx, src/domain/youthProfile/edit/__tests__/EditYouthProfile.test.tsx, src/domain/youthProfile/helpers/__tests__/updateProfileMutationVariables.test.ts, src/domain/youthProfile/helpers/updateProfileMutationVariables.ts, src/domain/youthProfile/hooks/useUpdateProfiles.ts, src/domain/youthProfile/sent/SentYouthProfile.tsx, src/domain/youthProfile/sent/__tests_/SentYouthProfile.test.tsx, src/graphql/generatedTypes.ts
This PR changes resend email, renew membership and edit profile information mutations to work with federation. 
`-`
[YM-390](https://helsinkisolutionoffice.atlassian.net/browse/YM-390)
Manually + `e2e`-tests (note that this branch is not up to date with development, where profile creation tests are skipped)
1) Create a youth profile (adult, emails are not yet received)
2) Editing youth profile data works
3) From jässäris django admin set expiration year to 2020
4) Expect renew button to show and pressing it renews membership succesfully
=> YM-390 | Edit mutations work with federation

CHANGELOG.md, src/domain/membership/information/MembershipInformation.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Adds a temporary link into the membership information page that leads users to a feedback form.
[YM-421](https://helsinkisolutionoffice.atlassian.net/browse/YM-421)
I've tested this locally by hand.
The current QA version of the profile API does not support this UI anymore so this is difficult to test. You'll have to use a local version of helsinki profile or mock some data locally.
=> YM-421 | Add temporary feedback link to membership info

CHANGELOG.md, src/domain/youthProfile/hooks/useCreateProfiles.ts
Previously the name query was not updated, which caused the user menu
to not receive the details of the newly created profile, which in turn
caused the link to the profile to go missing from the user menu.
[YM-441](https://helsinkisolutionoffice.atlassian.net/browse/YM-441)
I've tested this manually by registering a new youth profile and asserting that the user menu updated after the creation of the new profile.
As a non-logged in user without a profile
1. Input birthdate
1. Click log in
1. Input details
1. Register
1. Expect your name to be visible in the top right menu
1. Expect to see a link to Helsinki profile when you toggle the menu open
=> YM-441 | Refetch name query on profile creation

CHANGELOG.md, src/domain/youthProfile/approve/__test__/ApproveYouthProfileForm.test.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
After the year changed, the test data no longer represent an user of
the expected age. This is a quick fix that changes the user's birthday
so that they are the correct age.
The problem with this fix is that the snapshot test will break once the year changes again. The test should ideally be refactored so that it's not dependent on current time and would not break as time moves onwards.
`yarn test` passes without errors.
Ensure that CI tests pass.
=> Chore | Fix failing snapshot test

CHANGELOG.md, browser-tests/loginView.ts
The test data created a user that will be over 29 years after march, but assumed them to be over 30 already.
As a dirty fix I just changed their birthday into 01.01. Another approach would have been to find out the date that an exactly 30-year-old would be, but I am not sure if that would have been much better, and it would have required more work to implement.
[YM-444](https://helsinkisolutionoffice.atlassian.net/browse/YM-444)
I ran browser test against this branch: https://github.com/City-of-Helsinki/youth-membership-ui/actions/runs/482027598
Check that browser test have passed here: https://github.com/City-of-Helsinki/youth-membership-ui/actions/runs/482027598
=> YM-444 | Fix failing browser test

src/common/components/textInput/TextInput.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
The wrapper I added in #199 did not forward ref, which caused an error to be logged in the birthday input component.
1. Open the application without being logged in
2. Expect no ref error to be logged
=> FIX | Forward ref in TextInput integration

src/common/components/dateInput/DateInputGroup.tsx
The hds-core package had changed the way in which it applies error states. This PR changes the DateInput component to use that approach.
I've tested this manually.
1. Input a date that causes an error
2. Expect to see an error message
=> FIX | Fix incorrect error colour in DateInput

CHANGELOG.md, src/domain/youthProfile/form/YouthProfileForm.tsx
Replaced the `<Link> + <button>` combo with `LinkButton`, this removed excess button element.
Duplicate elements would cause confusion to users with screen reader.
[YM-404](https://helsinkisolutionoffice.atlassian.net/browse/YM-404)
Tested this manually with voice over + chrome.
1. While using screen reader, navigate to "Edit own information page"
2. Move to cancel button
3. Expect button text to be read once
=> YM-404 | Fix duplicate cancel button while editing own information

CHANGELOG.md, src/common/components/externalLink/ExternalLink.tsx, src/common/components/externalLink/__tests__/ExternalLink.tests.js, src/common/components/externalLink/__tests__/__snapshots__/ExternalLink.tests.js.snap, src/common/components/externalLink/externalLink.module.css, src/common/components/layout/footer/Footer.tsx, src/common/components/layout/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/common/components/linkButton/LinkButton.tsx, src/common/components/termsField/TermsField.tsx, src/domain/auth/components/login/Login.module.css, src/domain/auth/components/login/Login.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Replaces the links that open a new window with the "ExternalLink" component which includes an icon warning for visual users and a text warning for screen reader users.
[YM-399](https://helsinkisolutionoffice.atlassian.net/browse/YM-399)
I've tested the feedback link and the links within the terms field manually with Safari and VoiceOver and I've added unit tests for the `ExternalLink` component.
With a screen reader
1. Navigate to feedback link (footer area)
2. Expect to hear a warning about the link opening in a new tab
.
1. Navigate to user creation form
2. Expect all the links within the terms field label to warn that they open in a new tab
Note that labels containing links are not good for accessibility, but it's beyond the scope of this change.
=> YM-399 | Fix links that don't warn when opening a new window

CHANGELOG.md, src/common/components/dateInput/DateInputLogic.tsx
Using the number type would allow the arrow keys to be used in
selecting the content of a date part. This was however deemed too
confusing in the accessibility report.
[YM-396](https://helsinkisolutionoffice.atlassian.net/browse/YM-396)
I've tested this manually by using Safari and VoiceOver. There is no longer a mention of a spinner field, nor do the arrow keys work.
With a screen reader
1. Navigate to birthday input
2. Navigate through date input fields
3. Expect for fields to be described as text fields
4. Expect that up and down arrow don't change the value in the fields
=> YM-396 | Fix cognitively challenging date input

CHANGELOG.md, src/domain/membership/information/MembershipInformation.tsx, src/domain/membership/information/__tests__/MembershipInformationPage.test.tsx, src/domain/membership/information/membershipInformation.module.css
Wen't through the application with Siteimprove extension and manually. There was only one page where to order of headings was incorrect.
Inconsistent use of HTML headings make it difficult to navigate the application with screen reader.
[YM-403](https://helsinkisolutionoffice.atlassian.net/browse/YM-403)
I tested this manually.
Use extension like Siteimprove to help you. Manually check heading elements that they are in correct order.
=> YM-403 | Inconsistent HTML headings

CHANGELOG.md, src/common/components/dateInput/DateInput.tsx, src/common/components/dateInput/DateInputLogic.tsx, src/domain/auth/components/birthdateForm/BirthdateForm.tsx, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/form/YouthProfileApproverFields.tsx, src/domain/youthProfile/form/YouthProfileBasicInformationFields.tsx
By adding autocomplete attributes, we allow users to autocomplete or -fill form fields. This makes the forms more accessible, because it may be swifter for users to input values with autofill.
https://www.w3.org/TR/WCAG21/#input-purposes
[YM-395](https://helsinkisolutionoffice.atlassian.net/browse/YM-395)
I've tested this manually by applying the attributes based on the resource linked above and checking that they can be found from elements.
I find this feature difficult to test, because it's unclear what logic browsers user to autofill fields. For instance Chrome would autofill fields correctly even without specifying these attributes.
In general terms, this procedure can be followed to check all the changes in case you are able to find a sandbox where you can test strictly autocomplete: …
=> YM-395 | Allow form fields to be autocompleted

CHANGELOG.md, src/common/helpers/__tests__/yupErrorReconciler.test.js, src/common/helpers/yupErrorReconciler.ts, src/domain/app/BrowserApp.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/form/FormikTextInput.tsx, src/domain/youthProfile/youthProfileSchemas.ts, src/i18n/en.json, src/i18n/fi.json, src/i18n/i18nInit.ts, src/i18n/setYupLocale.ts, src/i18n/sv.json
Adds more descriptive error messages to forms which contain more details about what actions the user needs to take to remedy the situation.
Building on the previous assumptions, I attempted to create generic error messages that can be shared between fields. The upside is that there are fewer translation strings to maintain and fewer changes in the code, but the downside is that this approach entangles the translations with the code some more.
I would generally advise to use non-generic strings when the translation require more convoluted structures. I've applied field specific errors for instance to the email field.
[YM-397](https://helsinkisolutionoffice.atlassian.net/browse/YM-397)
I've tested this manually by going though the registration flow. I've added unit test to a new utility I …
=> YM-397 | Use more descriptive error messages on forms

CHANGELOG.md, src/domain/app/AppRoutes.tsx
Changed approver route to use `AppPageTitleRoute` component. I forgot to change when reworking routing components.
-
Tested this manually, route works.
- Have a profile that has pending confirmation and navigate to approval route. It should work normally.
=> FIX | Change approver route to use AppPageTitleRoute

.github/workflows/production.yml, .gitlab-ci.yml, CHANGELOG.md
Uses the public API for Jassari. The non-public endpoint may not be enabled for all users.
=> Chore | Use public Jassari API

.github/workflows/staging.yml
Enables `BASE_DOMAIN` environment variable for jobs so that complete urls can be built.
=> FIX | Enable BASE_DOMAIN to fix incomplete urls

.github/workflows/production.yml
Downrgades the production build configuration so that we can rebuild
the current production version which assumes that Jässäri has not yet
been separated from Helsinki profile.
After merging these changes, we can re-release production and it'll be built with config that are compatible with its vurrent version.
[YM-450](https://helsinkisolutionoffice.atlassian.net/browse/YM-450)
=> YM-450 | Fix production build

.env, src/domain/membership/graphql/MembershipInformation.graphql, src/domain/membership/information/__tests__/MembershipInformationPage.test.tsx, src/domain/youthProfile/graphql/HasYouthProfile.graphql, src/graphql/generatedTypes.ts
Fixed warning `apollo` was throwing related to data not having identifier. Also made changes to `.env` and pointed pointed authentication to KuVa tunnistamo.
=> Fix apollo warning

src/domain/youthProfile/form/YouthProfileForm.tsx, src/domain/youthProfile/form/youthProfileForm.module.css
A quick fix that changes `terms of service` title from `h3` to `h2` to make it inline with rest of the form.
=> HEL-403 | Fix terms heading

.github/workflows/review.yml, CHANGELOG.md, browser-tests/pages/loginSelector.ts, browser-tests/utils/login.ts
Runs acceptance tests against PR environments when a PR is opened.
In order to accomplish this I copied the approach used in Tapahtumat Helsinki. I also had to change Tunnistamo configurations in order to enable Helsinki Tunnus as a means of authentication.
I changed the login routine to contain logic that enables the test routine to accept permissions requests if such is prompted.
The tests have been ran in this PR.
Check that the test pass.
=> Chore | Run browser tests against PR environment

CHANGELOG.md, package.json, src/common/components/layout/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
The privacy policy links have changed and the ones currently in use no longer lead to anywhere.
[YM-455](https://helsinkisolutionoffice.atlassian.net/browse/YM-455)
I've checked that the links work by hand.
Check that the links are fixed in the footer and in the registration form.
=> Hotfix YM-455 | Update privacy policy links

CHANGELOG.md, src/i18n/en.json
Changes the English translation so that the approval view no longer contains inconsistent or gendered pronouns.
[YM-439](https://helsinkisolutionoffice.atlassian.net/browse/YM-439)
=> YM-439 | Fix gendered pronoun in approval confirmation view

.github/workflows/production.yml, CHANGELOG.md, package.json
`https://api.hel.fi/auth/jassariapiprod` should be used instead of `https://api.hel.fi/auth/jassariapi`
=> Release 1.3.2

CHANGELOG.md, src/domain/youthProfile/approve/ApproveYouthProfilePage.tsx
Fixes the photo usage approval boolean check.
It's a bit weird that a string value is used for the approval value, but I made the most minor change possible and just fixed the check.
[YM-466](https://helsinkisolutionoffice.atlassian.net/browse/YM-466)
Ensure that >=15 && <18 year old can deny photo usage.
=> YM-466 | Fix photo usage always being set as true

CHANGELOG.md, src/config.ts, src/domain/landingPage/LandingPage.tsx, src/domain/landingPage/YouthProfileApprovedTime.graphql, src/domain/membership/MembershipPageLayout.tsx, src/domain/membership/MembershipUtility.ts, src/domain/membership/graphql/MembershipInformation.graphql, src/domain/membership/information/MembershipInformation.tsx, src/domain/membership/information/MembershipInformationPage.tsx, src/domain/membership/information/__tests__/MembershipInformation.test.jsx, src/domain/membership/information/membershipInformation.module.css, src/domain/membership/membershipPageLayout.module.css, src/domain/membership/useMembershipStatus.ts, src/domain/youthProfile/create/CreateYouthProfilePage.tsx, src/domain/youthProfile/sent/__tests_/__snapshots__/SentYouthProfile.test.tsx.snap, src/graphql/generatedTypes.ts, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Previously the membership status of RENEWING was not reflected in the UI. It was also unclear which of the other states (ACTIVE, PENDING, EXPIRED) were handled to what degree.
As added complexity, we also want to show a slightly different UI for user's who are "adults" as opposed to when they are minors and need to have their membership approved.
As context, here are the different possible states:
**Membership status**  
PENDING -- Membership is not active and is awaiting approval from an approver  
ACTIVE -- Membership is active  
RENEWING -- Membership is active and is awaiting approval from an approver  
EXPIRED -- Membership has expired  
**On top of the status there other fields are used**  
`renewable` -- True when the membership can be renewed. True after `1.5` and until the …
=> YM-469 | Reflect membership status changes in membership info

CHANGELOG.md, src/domain/membership/MembershipPageLayout.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
User survey is over so we can remove the link to it.
[YM-478](https://helsinkisolutionoffice.atlassian.net/browse/YM-478)
I've manually verified that the link is missing.
=> YM-478 | Remove user survey feedback link

.env.example, .github/workflows/CI.yml, .github/workflows/review.yml, .github/workflows/staging.yml, CHANGELOG.md, src/__tests__/config.test.js, src/config.ts, src/i18n/I18nService.ts, src/i18n/__tests__/I18nService.test.js, src/logger.ts
Allows additional locales to be defined with `REACT_APP_ADDITIONAL_LOCALES` environment variable.
The format for the config is a string of comma separated ISO 639-1 values.
Locales found from the config are used to search for translation files, which are then configured for i18next.
Additional languages have been configured for use in review and staging environments. Users should expect to see error for missing locales.
[YM-487](https://helsinkisolutionoffice.atlassian.net/browse/YM-487)
I've added or modified unit level tests.
=> YM-487 | Option to define additional locales with environment variables

CHANGELOG.md, src/i18n/I18nService.ts, src/i18n/__tests__/I18nService.test.js
After this change, language direction is detected on language change and it is synced into the document by toggling the dir attribute in the HTML element.
[YM-484](https://helsinkisolutionoffice.atlassian.net/browse/YM-484)
I've added unit level tests to check that the behaviour.
=> YM-484 | Add support for language direction detection based on locale

src/common/components/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/common/components/layout/header/Header.tsx, src/common/components/layout/header/__tests__/__snapshots__/Header.test.tsx.snap, src/i18n/I18nService.ts, src/i18n/__tests__/I18nService.test.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Instead of using hardcoded values, the navigation uses the I18nService to find out which languages are supported.
Also adds language direction support into the language navigation options.
[YM-489](https://helsinkisolutionoffice.atlassian.net/browse/YM-489)
=> YM-489 | Use i18n service to find options for language menu

CHANGELOG.md, src/domain/auth/components/birthdateForm/BirthdateForm.module.css, src/domain/auth/components/login/Login.module.css, src/domain/auth/components/login/Login.tsx, src/domain/youthProfile/approve/approveYouthProfileForm.module.css, src/domain/youthProfile/create/createYouthProfile.module.css, src/domain/youthProfile/edit/editYouthProfile.module.css, src/domain/youthProfile/form/youthProfileForm.module.css
Either removes text align entirely or replaces `left` values with `initial` values, which allows the styling logic to correctly decide the non-centered text state based on the `dir` attribute in the html element.
[YM-486](https://helsinkisolutionoffice.atlassian.net/browse/YM-486)
I've tested the views manually. I wasn't able to test the approver view because mails still seem to have some issues.
=> YM-486 | Remove forced right aligns from text

CHANGELOG.md, package.json, src/domain/app/App.tsx, src/i18n/I18nService.ts, src/i18n/__tests__/I18nService.test.js, yarn.lock
After these changes, locales are registered within the I18nService, according to the supported languages. This integrates the i18n-iso-countries library into our I18nService, giving the country select the possibility to show options in supported languages.
[YM-493](https://helsinkisolutionoffice.atlassian.net/browse/YM-493)
=> YM-493 | Register locales within I18nService

CHANGELOG.md, package.json, src/i18n/ar.json, src/i18n/en.json, src/i18n/et.json, src/i18n/fi.json, src/i18n/fr.json, src/i18n/ru.json, src/i18n/so.json, src/i18n/sv.json
Adds placeholder translations into the translation sheets and pulls them into the service.
The update translations script was changed to ask for the additional langauges.
[YM-490](https://helsinkisolutionoffice.atlassian.net/browse/YM-490)
=> YM-490 | Add placeholder translations for fr, ru, et, so and ar

src/domain/youthProfile/hooks/useCreateProfiles.ts
Due to open-city-profile deprecating some old behavior, the order of the calls is changed when registering a new member to:
1. Create Helsinki profile
2. Add connection to Youth membership service
3. Create Youth profile
The last call eventually also calls the Helsinki profile in the youth membership backend. The service connection needs to be created into Helsinki profile before the youth membership profile creation call is made.
[YM-512](https://helsinkisolutionoffice.atlassian.net/browse/YM-512) Change the order in which the service connection to Youth membership is made
I used the latest development branch of open-city-profile, which doesn't have the implicit connection feature/logic anymore, which allowed the old way of creating the youth membership profile before the service …
=> YM-512 | Reorder GraphQL calls for creating youth membership

src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/helpers/__tests__/createProfileMutationVariables.test.ts
When yet another year has passed, the age calculation now failed. Changed the calculation to be dynamic.
Required for tests to pass.
=> Fixed the age tests and snapshots
