Dockerfile, README.md, docker-compose.yml, package.json
Create very simple docker dev-env (shamelessly copied from berth-reservations-ui)
Remove eject from scripts and readme, it can still be done but it's unnecessary to mention it.
=> OM-46 create docker dev env

.eslintrc.json, .prettierrc.json, package.json, src/App.test.tsx, src/App.tsx, src/BrowserApp.tsx, src/common/header/Header.tsx, src/common/layout/PageLayout.tsx, src/i18n/i18nInit.ts, src/index.tsx, src/pages/Home.tsx, yarn.lock
Better and more beautiful linting rules from kukkuu-ui
=> Stricter linting rules

.dockerignore, .env, .env.test, .gitlab-ci.yml, .prod/nginx.conf, Dockerfile, docker-compose.yml
Changed the Docker configs based on what was configured in the
kukkuu-ui application. These should now include a nginx config
for the health check endpoints. Added a yaml file for Gitlab.
The values in the configs are mostly guesses. We'll see how this
plays out in the actual CI build.
=> OM-236 | Add configuration for CI pipelines

src/graphql/__generated__/globalTypes.ts, src/pages/memberhsip/components/approveYouthProfileForm/ApproveYouthProfileForm.tsx, src/pages/memberhsip/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/memberhsip/components/createYouthProfileForm/CreateYouthProfileForm.tsx, src/pages/memberhsip/components/youthProfile/YouthProfile.tsx, src/pages/memberhsip/graphql/AddServiceConnection.graphql, src/pages/memberhsip/graphql/__generated__/AddServiceConnection.ts, src/pages/tos/components/termsOfService/TermsOfService.tsx
- Added addServiceConnection mutation
- Changed ProfileExistsQuery from lazy to normal (this query will be executed automatically after addServiceConnection mutation)
- Includes OM - 358 -> When clicking terms of service link inside form, page opens on new tab
=> OM - 377 | Registration doesn't add service connection 

package.json, src/pages/membership/components/approveYouthProfile/ApproveYouthProfile.tsx, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/membershipDetails/MembershipDetails.tsx, src/pages/membership/components/membershipInformation/MembershipInformation.module.css, src/pages/membership/components/membershipInformation/MembershipInformation.tsx, src/pages/membership/components/sentYouthProfile/SentYouthProfile.tsx, src/pages/membership/components/youthProfile/YouthProfile.tsx, yarn.lock
- Added basic error handling for apollo hooks
- Added QRCode to MembershipInformation view.
=> OM - 369 | Handle errors on backend call

src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/createYouthProfileForm/CreateYouthProfileForm.tsx
- Removed comments from langaugeAtHome field
- Changed photoUsageApproved value to string inside form.
=> Om - 421 | Send language at home

src/auth/components/birthdateForm/BirthdateForm.module.css, src/auth/components/birthdateForm/BirthdateForm.tsx, src/auth/components/login/Login.module.css, src/auth/components/login/Login.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/createYouthProfileForm/CreateYouthProfileForm.module.css, src/pages/membership/components/createYouthProfileForm/CreateYouthProfileForm.tsx, src/pages/membership/helpers/getCookie.ts
Includes tickets
- OM - 443
- OM - 464
Before authentication user needs to input their age. If user is under 13, page with manual registration information is shown. If age is between 13 and 25 user is the redirected to authentication. 
Editing age in registration form is removed and age input before authentication is shown on the page. Registration form has more age restrictions:
- User is under 15, photoUsage fields are hidden.
- User is 15 or over, photoUsage fields are show.
- User is 18 or over, information texts about sending approval email & requiring guardian approval are hidden.
=> OM - 440 | Move birthday input to login page

.env.development, src/pages/membership/components/approveYouthProfileForm/ApproveYouthProfileForm.tsx, src/pages/membership/constants/ageConstants.ts
If applicant is under 15 years old, photo permission options are shown to guardian, else they are hidden.
=> OM - 402 | Approval form photo permission

src/auth/authenticate.ts, src/auth/components/login/Login.tsx, src/auth/redux.ts
If tunnistamo authentication throws error, notification is shown to user.
=> OM - 474 | Added error handling on tunnistamo call

src/auth/components/login/Login.module.css, src/auth/components/login/Login.tsx, src/auth/logout.ts, src/common/header/userDropdown/UserDropdown.tsx, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/youthProfile/YouthProfile.tsx
If birthDate is missing from cookies, user will always be redirected to login page. BirthDate value is reset to empty during logout process. This will help in cases where two people wan't to register one after another using same computer.
=> OM - 478 | User can skip to registration form

package.json, src/common/notification/NotificationComponent.module.css, src/common/notification/NotificationComponent.tsx, src/common/test/testUtils.tsx, src/graphql/generatedTypes.ts, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/membership/components/membershipInformation/MembershipInformation.tsx, src/pages/membership/components/membershipInformation/__tests__/MembershipInformation.test.tsx, src/pages/membership/components/youthProfile/YouthProfile.tsx, src/pages/membership/graphql/HasYouthProfile.graphql, src/pages/membership/graphql/MembershipInformation.graphql, src/pages/membership/helpers/getFullName.ts, src/setupTests.ts, yarn.lock
Includes tickets 
- OM - 495
- OM - 492
Renew button is shown based on value returned from backend. Successful renew shows notification and refreshes expiration date. To test this functionality, change expiration date in django admin to point year, 2019 for example.
NotificationComponent 
- Added style to close button so it doesn't appear on top of the title text.
- Changed import method for DismissableNotification. Previous method `import { DismissableNotification } from 'hds-react'` would crash during testing.
Tests
- Added tests for MembershipInformation component
- This required installing extra package to help jest render component with canvas.
=> OM - 494 | Update view after renew

src/auth/components/login/Login.module.css, src/auth/components/login/Login.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Added back button for under 13 years old view. Now user can return to view that asks birthdate without reloading page.
=> OM - 498 | Add back button 

src/graphql/generatedTypes.ts, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/createYouthProfileForm/CreateYouthProfileForm.tsx
photoUsageApproved values are uncommented.
=> OM - 480 | photoUsageApproved value is sent to backend

src/auth/components/login/Login.tsx, src/auth/constants/authConstants.ts, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Added link that opens registration form to new page. Also changed hard coded age & url values to constants.
=> OM - 523 | Add link to downloadable pdf

.env, package.json, src/auth/authenticate.ts, src/auth/components/oidcCallback/OidcCallback.tsx, src/auth/logout.ts, src/index.tsx, src/pages/membership/components/approveYouthProfile/ApproveYouthProfile.tsx, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/membershipDetails/MembershipDetails.tsx, src/pages/membership/components/membershipInformation/MembershipInformation.tsx, src/pages/membership/components/sentYouthProfile/SentYouthProfile.tsx, src/pages/membership/components/youthProfile/YouthProfile.tsx, yarn.lock
- Added configurations to initialize Sentry
- Added Sentry error capturing to login, logout, queries and mutations.
=> OM - 340 | Configure sentry

package.json, yarn.lock
=> OM - 571 | Add codecov

src/common/dropdown/Dropdown.module.css, src/common/dropdown/Dropdown.tsx, src/common/header/userDropdown/UserDropdown.tsx
Header only shows users first name and if it's too long it will be truncated with ellipsis.
=> OM - 561 | Reduce shown name length in header.

src/graphql/generatedTypes.ts, src/pages/membership/components/membershipDetails/MembershipDetails.tsx, src/pages/membership/graphql/MembershipDetailsFragment.graphql
Profile language is now show in youth's detailed view.
=> OM - 621 | Add profile language to detail's view

src/i18n/en.json, src/pages/membership/components/createYouthProfileForm/CreateYouthProfileForm.tsx
- Added validation to school name (128 characters)
- Added validation to school class (10 characters)
- Fixed English translation for school class.
=> OM - 625 | School class allows too long value

cypress.json, cypress/integration/login_page.ts, cypress/plugins/index.ts, cypress/support/commands.ts, cypress/support/index.ts, cypress/tsconfig.json, package.json, src/auth/components/login/Login.tsx, yarn.lock
- Added Cypress.io to project for end-to-end testing. 
- Wrote tests for login page.
I wasn't able to solve issue with imports and exports, I'll do that later as agreed with the team.
=> OM - 570 | Add Cypress.io

src/common/footer/Footer.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Added target for "Give feedback" - link.
=> OM - 668 | Added target for footer's feedback link.

package.json, public/index.html, public/robots.txt, src/common/layout/PageLayout.tsx, src/common/layout/__tests__/PageLayout.test.tsx, src/common/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, yarn.lock
Most of the texts are just placeholders for now & all the images and twitter related stuff will be added later. I added `Disallow: /` to robots.txt, which should block search engine access for now.
=> OM-535 | SEO optimization.

CONTRIBUTING.md, README.md
- Updated links
- Added instructions for contributing.
- Changed scripts instructions to use yarn instead of npm.
=> OM-528 | Update README

src/App.tsx, src/auth/components/login/Login.tsx, src/common/footer/Footer.tsx, src/common/layout/PageLayout.tsx, src/common/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/common/wrapper/PageWrapper.tsx, src/common/wrapper/__tests__/PageWrapper.test.tsx, src/common/wrapper/__tests__/__snapshots__/PageWrapper.test.tsx.snap, src/pages/accessibilityStatement/AccessibilityStatement.module.css, src/pages/accessibilityStatement/AccessibilityStatement.tsx, src/pages/accessibilityStatement/AccessibilityStatementEn.tsx, src/pages/accessibilityStatement/AccessibilityStatementFi.tsx, src/pages/accessibilityStatement/AccessibilityStatementSv.tsx
Added initial accessibility statements. I went with the same approach as kukkuu-ui, where each language has it's own component.
=> OM-736 | Add initial accessibility statements.

src/index.tsx
Change sentry environment to use gitlab variables.
=> YM-192 | Sentry environment is always production

src/i18n/languageSwitcher/LanguageSwitcher.tsx
Changed language order, current language is not shown.
=> YM-198 | Language selection changes.

src/auth/userManager.ts
User session is now saved to localStorage and available in new tab.
=> YM-207 | User session is not saved

src/pages/tos/constants/tosConstants.ts
Update links to up-to-date ones.
=> YM-186 | Fix broken privacy policy links

src/common/helpers/__tests__/getLanguageCode.test.ts, src/common/helpers/getLanguageCode.ts, src/pages/membership/components/youthProfileForm/YouthProfileForm.tsx, src/pages/membership/helpers/__tests__/getAddress.test.ts, src/pages/membership/helpers/getAddress.ts
- Fixes country dropdown when language data contains locale
- Fixes country rendering for address when language data contains locale
- Fixes unneeded commas being rendered for address
=> YM-216 | Fix country dropdown

src/pages/membership/components/approveYouthProfile/__test__/ApproveYouthProfile.test.tsx
Added few tests for `ApproveYouthProfile` component. I didn't add snapshot, mainly because `MockedProvider` adds mysterious object that is randomly added / removed.
=> YM-255 | Add tests for ApproveYouthProfile

src/pages/membership/components/approveYouthProfileForm/__tests__/ApproveYouthProfileForm.test.tsx, src/pages/membership/components/approveYouthProfileForm/__tests__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
Added few tests for `ApproveYouthProfileForm` component.
=> YM-226 | Tests for ApproveYouthProfileForm.

src/common/header/Header.tsx, src/common/helsinkiLogo/HelsinkiLogo.module.css, src/common/helsinkiLogo/HelsinkiLogo.tsx, src/common/helsinkiLogo/__tests__/HelsinkiLogo.test.tsx
- Helsinki logo is now a link that points to home page.
- Added margin between swedish logo & service name
=> OM-200 | Logo is now a link

src/common/test/testUtils.tsx, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/createYouthProfile/__tests__/CreateYouthProfile.test.tsx
- Tests for `CreateYouthProfile` component.
- Fixed typo in component name 
- Added `getLanguageCode` helper to language values.
=> YM-229 | Tests for CreateYouthProfile

src/auth/components/login/Login.module.css, src/auth/components/login/Login.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/membership/components/approveYouthProfileForm/__tests__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
- Updated translations
- Fixed button behaviour in under 13 years page.
=> YM-240 | Jässäri buttons break on mobile 

src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/membership/components/approveYouthProfileForm/__tests__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
Added link to data protection principles.
=> YM-219 | Update data protection link

src/common/header/Header.module.css, src/common/header/Header.tsx
- After these changes App name in header is a link to home page.
=> YM-200 | App name in header is not link

.gitlab-ci.yml
Profile link now points to automatic authentication url.
PR making changes to [Profile](https://github.com/City-of-Helsinki/open-city-profile-ui/pull/92)
=> YM-233 | Change profile link

src/common/test/membershipDetailsData.ts, src/pages/membership/components/editYouthProfile/__tests__/EditYouthProfile.test.tsx
Few simple tests for `EditYouthProfile` component.
=> OM-859 | Tests for EditYouthProfile

src/common/dropdown/Dropdown.tsx, src/common/dropdown/__tests__/DropDown.test.tsx, src/common/dropdown/__tests__/__snapshots__/DropDown.test.tsx.snap
Added few tests for `DropDown` component.
=> YM-245 | Test for SentYouthProfile

src/pages/membership/components/sentYouthProfile/__tests_/SentYouthProfile.test.tsx, src/pages/membership/components/sentYouthProfile/__tests_/__snapshots__/SentYouthProfile.test.tsx.snap
Tests for `SentYouthProfile` component.
=> YM-244 | Test for SentYouthProfile

.gitlab-ci.yml, package.json
Fixed the URLs pointing at Helsinki profile in production. Also changed
the version number so that it's now OK for release candidate 1.
=> YM-241 | Fix production config

src/common/footer/__tests__/Footer.test.tsx, src/common/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/common/header/__tests__/Header.test.tsx, src/common/header/__tests__/__snapshots__/Header.test.tsx.snap
Added simple snapshot tests for both components.
=> YM-246 | Tests for Header and Footer.

.env, package.json
Production environment configs for Tunnistamo changed, I updated them
to .env.
I also bumped up the version.
=> Fix production config for authentication

.env, package.json
Messed up the config last time, here's another try at the client id.
=> Fix production authentication config

.env, package.json
Prod configuration was tweaked in master branch, so merging those changes back into develop.
=> Merge hotfixes from master

src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
=> YM-252 | Update translations

CHANGELOG.md, package.json, src/pages/membership/components/createYouthProfile/CreateYouthProfile.tsx, src/pages/membership/components/editYouthProfile/EditYouthProfile.tsx, src/pages/membership/components/youthProfileForm/FormikTextInput.tsx, src/pages/membership/components/youthProfileForm/YouthProfileForm.tsx, src/pages/membership/components/youthProfileForm/__tests__/FormikTextInput.test.tsx, src/pages/membership/components/youthProfileForm/__tests__/YouthProfileForm.test.tsx, src/pages/membership/helpers/__tests__/createProfileMutationVariables.test.ts, src/pages/membership/helpers/__tests__/updateProfileMutationVariables.test.ts, src/pages/membership/helpers/createProfileMutationVariables.ts, src/pages/membership/helpers/updateProfileMutationVariables.ts, yarn.lock
This way we avoid situations where the form does not send due to an
error, but the error is out of screen for the user, causing confusion.
----
As far as I can tell, there were no other inputs than `TextInput`s which could end up in an erroneous state.
=> YM-243 | Validate youth profile form fields on blur

src/domain/app/AppRoutes.tsx
Accessibility statement and not found pages would not work with this
component included.
=> Fix missing pages

package.json, src/domain/youthProfile/form/FormikFocusError.tsx, src/domain/youthProfile/form/YouthProfileForm.tsx, src/domain/youthProfile/form/youthProfileForm.module.css, yarn.lock
- Submit button is always clickable (removed disabled status if terms was not accepted)
- Added error text form terms
- If error occurs, form will be autoscrolled to first invalid element.
=> YM-267 | Scroll to first error

src/domain/youthProfile/form/youthProfileFormSchema.ts
I had forgotten to update the schema to enforce validation rules for additionalContactPersons.
=> YM-86 | Add missing validation

src/domain/youthProfile/helpers/__tests__/createProfileMutationVariables.test.ts, src/domain/youthProfile/helpers/youthProfileGetters.ts
The creation mutation contains field the backend does not expect.
=> Fix profile creation

src/common/components/basicInformationGrid/BasicInformationGrid.tsx, src/common/components/basicInformationGrid/basicInformationGrid.module.css, src/common/components/labeledValue/LabeledValue.module.css, src/common/components/labeledValue/LabeledValue.tsx, src/common/components/stack/Stack.tsx, src/common/components/stack/stack.module.css, src/common/components/termsField/TermsField.tsx, src/common/components/termsField/termsField.module.css, src/common/components/text/Text.tsx, src/common/components/text/text.module.css, src/domain/app/AppRoutes.tsx, src/domain/youthProfile/approve/ApproveYouthProfile.tsx, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/ApproveYouthProfilePage.tsx, src/domain/youthProfile/approve/ConfirmApprovingYouthProfile.tsx, src/domain/youthProfile/approve/__test__/ApproveYouthProfilePage.test.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/approve/__test__/__snapshots__/ConfirmApprovingYouthProfile.test.tsx.snap, src/domain/youthProfile/approve/approveYouthProfileForm.module.css, src/domain/youthProfile/form/YouthProfileForm.tsx
I fixed a few small bugs:
- With no school and class a rogue comma would be shown
- Clicking on the checkbox label text would not toggle the checkbox
Beyond these changes I also:
- Removed the disabled attribute from the submit button (accessibility)
- Changed how additional addresses are rendered (talked a few details over with Anniina)
- Refactored the code
=> YM-264 | Update approval view

src/common/components/basicInformationGrid/BasicInformationGrid.tsx, src/common/components/infoGrid/InfoGrid.tsx, src/common/components/infoGrid/InfoGridRow.tsx, src/common/components/infoGrid/infoGrid.module.css, src/domain/membership/details/MembershipDetails.tsx, src/domain/membership/details/__tests__/MembershipDetailsPage.test.tsx, src/domain/membership/details/membershipDetails.module.css, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
This way fixing one fixes the other and the views don't fall out of
sync when it comes ot basic details.
=> Use same component in details and approval view

CHANGELOG.md, src/common/components/basicInformationGrid/BasicInformationGrid.tsx, src/domain/membership/details/MembershipDetails.tsx, src/domain/youthProfile/approve/ApproveYouthProfile.tsx, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/__test__/ApproveYouthProfileForm.test.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap
Previously profile language was not shown in approval view.
=> YM-317 | Fix missing profile language in approval view

src/common/components/arrayFieldTemplate/ArrayFieldTemplate.tsx, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/form/FormGroupDescription.tsx, src/domain/youthProfile/form/YouthProfileApproverFields.module.css, src/domain/youthProfile/form/YouthProfileApproverFields.tsx, src/domain/youthProfile/form/YouthProfileForm.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Additional information text is show, if multiple guardians are added.
=> YM-347 | Add helpers text relating to additional approvers

CHANGELOG.md, public/index.html, src/common/components/wrapper/PageWrapper.tsx, src/common/components/wrapper/__tests__/__snapshots__/PageWrapper.test.tsx.snap, src/domain/app/App.tsx, src/domain/app/AppMeta.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Updates the index.html file to contain the updated meta description.
I also slightly refactored the `PageWrapper`. Application language is now synced closer to root and `PageWrapper` only contains meta tags that could, in the future, be page specific.
=> YM-358 | Update meta description

.github/PULL_REQUEST_TEMPLATE.md
I've added a PR template file.
This file will make it easier for the developer to provide all the relevant information in a consistent format.
No Jira ticket.
This has been tested by using Visual Studio Code's preview. The template has also been dogfooded for this PR description.
This template can be tested only after it has been merged into develop.
=> Chore | Add PR template

CHANGELOG.md, package.json
This PR contains the changes maded during the release of Youth membershpi UI 1.1.0, i.e. version number and changelog.
[YM-373](https://helsinkisolutionoffice.atlassian.net/browse/YM-373)
N/A
N/A
N/A
=> YM-373 | Bump version number and update changelog

src/domain/app/AppYouthProfileRoute.tsx, src/domain/auth/constants/authConstants.ts
Reverted previous changes. `useQuery` hook is back and errors related to permission are ignored.
Changes are necessary to restore correct routing. 
[YM-385](https://helsinkisolutionoffice.atlassian.net/browse/YM-385)
Tested profile creation manually and with `e2e` - tests. Tests do now cover 100% functionality yet, but they are better than nothing.
If application is opened in incognito for example, permission error is show but it shouldn't crash the application.
=> YM-385 | Routing is broken

CHANGELOG.md, package.json
This PR contains the changes maded during the release of Youth membershpi UI 1.1.1, i.e. version number and changelog.
[YM-386](https://helsinkisolutionoffice.atlassian.net/browse/YM-386)
N/A
N/A
N/A
=> YM-386 | Bump version number and update changelog

CHANGELOG.md, package.json
I updated the changelog and version number for the upcoming release.
[YM-419](https://helsinkisolutionoffice.atlassian.net/browse/YM-419)
N/A
Check out the changed files.
N/A
=> YM-419 | Bump version number and update changelog

src/domain/auth/redux.ts, src/domain/youthProfile/create/CreateYouthProfile.tsx, src/domain/youthProfile/create/__tests__/CreateYouthProfilePage.test.tsx, src/domain/youthProfile/graphql/CreateMyProfile.graphql, src/domain/youthProfile/graphql/CreateMyYouthProfile.graphql, src/domain/youthProfile/graphql/UpdateMyProfile.graphql, src/domain/youthProfile/helpers/__tests__/createProfileMutationVariables.test.ts, src/domain/youthProfile/helpers/createProfileMutationVariables.ts, src/domain/youthProfile/helpers/youthProfileGetters.ts, src/domain/youthProfile/hooks/useCreateProfiles.ts, src/graphql/__tests__/client.test.ts, src/graphql/generatedTypes.ts
Profile creation now works with federation. 
Fixed eslint warnings that I missed last time.
`-`
[YM-389](https://helsinkisolutionoffice.atlassian.net/browse/YM-389)
This has only been tested manually for now.
1) Navigate localhost
2) Enter birthdate and login
3) Fill the registration and submit form
4) Expect to land either on "Application send" or "Membership information" page
=> YM-389 | Change registration to work with federation

CHANGELOG.md, package.json
- Temporary feedback link button in membership information page
=> [Develop] Release 1.2.1

src/domain/app/AppYouthProfileRoute.tsx, src/domain/membership/helpers/__tests__/getAddress.test.ts, src/domain/membership/helpers/__tests__/getAddresses.test.ts
Fixes lint warnings that are currently in the application
I've ran `yarn lint` locally and it passed without warnings.
Expect GitHub code changes view to contains no lint warnings.
=> Fix lint warnings

CHANGELOG.md
I forgot to update the readme in https://github.com/City-of-Helsinki/youth-membership-ui/pull/201
[YM-402](https://helsinkisolutionoffice.atlassian.net/browse/YM-402)
[YM-400](https://helsinkisolutionoffice.atlassian.net/browse/YM-400)
[YM-401](https://helsinkisolutionoffice.atlassian.net/browse/YM-401)
=> Update navigation changes into readme

package.json, src/common/components/layout/header/Header.tsx, src/common/test/testUtils.tsx, src/domain/app/App.tsx, src/domain/app/AppYouthProfileRoute.tsx, src/domain/membership/details/MembershipDetailsPage.tsx, src/domain/membership/information/MembershipInformationPage.tsx, src/domain/membership/useIsMembershipPending.ts, src/domain/youthProfile/approve/ApproveYouthProfilePage.tsx, src/domain/youthProfile/approve/__test__/ApproveYouthProfilePage.test.jsx, src/domain/youthProfile/approve/__test__/useProfileByTokens.test.js, src/domain/youthProfile/approve/useProfileByTokens.ts, src/domain/youthProfile/create/CreateYouthProfilePage.tsx, src/domain/youthProfile/create/__tests__/CreateYouthProfilePage.test.tsx, src/domain/youthProfile/edit/EditYouthProfile.tsx, src/domain/youthProfile/hooks/useCreateProfiles.ts, src/domain/youthProfile/hooks/useUpdateProfiles.ts, src/domain/youthProfile/sent/SentYouthProfile.tsx, src/graphql/__tests__/client.test.ts, src/graphql/__tests__/handleError.test.ts, src/graphql/client.ts, src/graphql/handleError.ts, yarn.lock
Updates Apollo from major version 2 into major version 3.
Apollo changed its package structure in conjunction with this change, which in turn caused some churn.
I've completed the registration flow for a new user and it worked. I've checked the test suite and linters.
=> Chore | Update Apollo from branch 2 to branch 3

browser-tests/pages/loginSelector.ts
One selector had fallen out of date since the HDS upgrade. It's now updated and browser tests should pass.
https://github.com/City-of-Helsinki/youth-membership-ui/actions/runs/518272513
=> FIX | Fix browser tests

.github/workflows/production.yml
=> Fix a typo in variable name: K8S_ADDITIONAL_HOSTNAMES

.github/workflows/production.yml, .github/workflows/review.yml, .github/workflows/staging.yml, .github/workflows/stop_review.yml
=> Add workflow files for CI/CD pipeline

.github/workflows/production.yml
Updates the production config to master as well.
=> HOTFIX | Fix production config

.github/workflows/production.yml
This reverts commit 890c02199cb13b0545aa22d11a78eb4bf47e3e69.
Reverts production configuration change in order to prepare separated Jassari for release.
[YM-452](https://helsinkisolutionoffice.atlassian.net/browse/YM-452)
=> Revert "Fix production build"

CHANGELOG.md, package.json
Sync develop documentation to contain information about hotfixes used to configure the new GitHub workflow.
=> Chore | Update documentation

CHANGELOG.md, package.json, src/common/components/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/common/components/layout/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
We fixed a privacy policy link in production with a hotfix because we have things in development we do not want to release yet. This PR adds those changes into develop as well.
=> Chore | Merge YM-455 changes to develop

src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
I fixed the translation sources within the Google sheet, and then pulled the changes into the application.
All of the issues were due to line change characters, likely enter.
[YM-422 ](https://helsinkisolutionoffice.atlassian.net/browse/YM-422 )
=> YM-422 | Fix translation processing

.github/workflows/production.yml, CHANGELOG.md, package.json
- Incorrect federation location
=> Release 1.3.1

src/domain/membership/MembershipUtility.ts, src/domain/membership/information/MembershipInformation.tsx, src/domain/membership/information/MembershipInformationPage.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Add a custom success message for minors which tells them the renewal request has been sent for approval.
[YM-469](https://helsinkisolutionoffice.atlassian.net/browse/YM-469)
=> YM-469 | Add custom success message for minors

src/common/components/dateInput/DateInputLogic.tsx, src/domain/auth/components/birthdateForm/__tests__/BirthdateForm.test.js
Improves coverage of birthday form.
=> Chore | Birthday form coverage

src/domain/auth/__tests__/redux.js, src/serviceWorker.ts
Adds tests for auth state selectors, reducers and thunks.
=> Chore | Add tests to auth state

src/i18n/__tests__/I18nService.test.js, src/i18n/__tests__/setYupLocale.test.js, src/i18n/setYupLocale.ts
=> Chore | Add tests to i18n module

src/domain/app/App.tsx, src/domain/auth/userManager.ts, yarn.lock
Resolves high and moderate security warnings.
I wasn't able to reproduce the build failure locally, but I would have applied the fix I used in this PR regardless. I attemtped a fresh install of the application.
=> Chore | Resolve security warnings

.github/workflows/production.yml, CHANGELOG.md, package.json
Merges master to develop to add missing commits from master into develop.
=> Merge master to develop

CHANGELOG.md, browser-tests/pages/membershipInformationSelector.ts, package.json, src/domain/membership/details/MembershipDetails.tsx, src/domain/membership/details/__tests__/MembershipDetailsPage.test.tsx, src/domain/membership/details/membershipDetails.module.css, src/domain/youthProfile/approve/ApproveYouthProfileForm.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/form/FormikSelect.tsx, src/domain/youthProfile/form/FormikTextInput.tsx, src/domain/youthProfile/form/YouthProfileAdditionalInformationFields.tsx, src/domain/youthProfile/form/YouthProfileApproverFields.tsx, src/domain/youthProfile/form/useField.ts, src/domain/youthProfile/form/youthProfileForm.module.css, src/domain/youthProfile/youthProfileSchemas.ts, src/i18n/ar.json, src/i18n/en.json, src/i18n/et.json, src/i18n/fi.json, src/i18n/fr.json, src/i18n/ru.json, src/i18n/so.json, src/i18n/sv.json, yarn.lock
With this change
1) New options are added to the language at home field (Frnech, Russian, Somali, Arabic, Estonian)
2) The radio select is changed into a dropdown select
3) The field is moved to be shown in conjunction with the approver fields
4) The field is renamed into "preferred contact language"
[YM-498](https://helsinkisolutionoffice.atlassian.net/browse/YM-498)
https://share.goabstract.com/2de6ae0c-e30f-408c-8ab0-e4441d95fbdf 
https://share.goabstract.com/20b23d08-a13b-4a43-bb29-716d239e0d85
https://share.goabstract.com/c1adc2c1-e4f8-4145-a0eb-2b3d2d7219bd
I've amended existing tests to take these changes into account. I've manually tested the changes.
=> YM-498 | Change language at home field to preferred contact language field

src/common/components/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/common/components/layout/header/__tests__/__snapshots__/Header.test.tsx.snap, src/config.ts, src/i18n/__tests__/I18nService.test.js
List Estonian as the last language instead of the third.
=> Use same language order as is used in Mun Stadi page

src/domain/membership/details/__tests__/MembershipDetailsPage.test.tsx, src/domain/youthProfile/approve/__test__/__snapshots__/ApproveYouthProfileForm.test.tsx.snap, src/domain/youthProfile/create/__tests__/CreateYouthProfilePage.test.tsx, src/i18n/ar.json, src/i18n/en.json, src/i18n/et.json, src/i18n/fi.json, src/i18n/fr.json, src/i18n/ru.json, src/i18n/so.json, src/i18n/sv.json
Changes copy to more clearly communicate purpose of field.
[YM-499](https://helsinkisolutionoffice.atlassian.net/browse/YM-499)
=> YM-499 | Change copy profile language to preferred language

CHANGELOG.md, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Update links to youth membership application form.
After this PR gets merged, I will make a new release.
1) Enter the page that has a button for downloading application form
2) Test with all three languages. Dates on the form should be 1.8.2021–31.7.2022
=> RELEASE | Update links to youth membership application form.

src/domain/youthProfile/hooks/useCreateProfiles.ts
=> Release YM-512 / #288

CHANGELOG.md, src/i18n/ar.json, src/i18n/en.json, src/i18n/et.json, src/i18n/fi.json, src/i18n/fr.json, src/i18n/ru.json, src/i18n/so.json, src/i18n/sv.json
This PR backports changes from master (and also applies them to the new languages added in develop).
=> Merge changes from master

azure-pipelines-release.yml, azure-pipelines-review.yml, azure-pipelines-test.yml
[DEVOPS-487](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487)
[DEVOPS-487]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Azure pipelines

.prod/nginx.conf, Dockerfile
[DEVOPS-487](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487)
[DEVOPS-487]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Platta deployment Openshift write accesses

Dockerfile
[YM-517](https://helsinkisolutionoffice.atlassian.net/browse/YM-517)
[YM-517]: https://helsinkisolutionoffice.atlassian.net/browse/YM-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade to node14 YM-517

CHANGELOG.md
=> chore: remove invalid comments from changelog

browser-tests/editMembershipInformationView.ts, browser-tests/loginView.ts, browser-tests/pages/loginSelector.ts, src/domain/auth/components/login/Login.module.css, src/domain/auth/components/login/Login.tsx, src/i18n/ar.json, src/i18n/en.json, src/i18n/et.json, src/i18n/fi.json, src/i18n/ru.json, src/i18n/so.json, src/i18n/sv.json
=> feat: service not available

src/domain/auth/components/login/Login.tsx
=> fix: remove extra login text
